# Use a Python base image with the desired Python version
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Install system dependencies required by PySide6
RUN apt-get update && apt-get install -y \
    python3-pip \
    build-essential \
    libgl1-mesa-glx \
    libxcb-xinerama0 \
    libxcb-icccm4 \
    libxcb-image0 \
    libxcb-render-util0

# Install PySide6 using pip
RUN pip install PySide6

# Copy your application code into the container
COPY . .

# Set the command to run your application
CMD ["python", "bin/studio.py"]